package com.example.coop_vsit_hub.user_and_auth.enums;

/**
 * Security Audit Event Types for CoopBank Security Compliance.
 */
public enum AuditEventType {
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    ACCOUNT_LOCKED,
    ACCOUNT_UNLOCKED,
    TOKEN_REFRESH,
    LOGOUT,
    PASSWORD_CHANGE,
    UNAUTHORIZED_ACCESS,
    STAFF_REGISTERED,
    USER_UPDATED,
    USER_ROLES_UPDATED,
    USER_STATUS_UPDATED,
    USER_DELETED,
    VISIT_CREATED,
    VISIT_UPDATED,
    VISIT_STATUS_CHANGED,
    VISITOR_CHECKED_IN,
    VISITOR_CHECKED_OUT,
    VISIT_DELETED,
    ORGANIZATION_CREATED,
    ORGANIZATION_UPDATED,
    ORGANIZATION_DELETED,
    GUEST_CREATED,
    GUEST_UPDATED,
    GUEST_DELETED
}
